replicaCount: 1

image:
  repository: bobdatascientest/jenkinsexam
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 80
  # nodePort: 30001  # Allow Kubernetes to automatically assign the NodePort

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: "3.252.223.225"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

volumes:
  - name: movie-service-volume
    persistentVolumeClaim:
      claimName: movie-service-pvc
  - name: cast-service-volume
    persistentVolumeClaim:
      claimName: cast-service-pvc

volumeMounts:
  - name: movie-service-volume
    mountPath: /app/movie-service
  - name: cast-service-volume
    mountPath: /app/cast-service

nodeSelector: {}

tolerations: []

affinity: {}

